---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
Little Birds are dining    
Warily and well,    
Hid in mossy cell:    
Hid, I say, by waiters    
Gorgeous in their gaiters -    
I've a Tale to tell.  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
Whose woods these are I think I know      
His house is in the village though;      
He will not see me stopping here      
To watch his woods fill up with snow.      
      
My little horse must think it queer      
To stop without a farmhouse near      
Between the woods and frozen lake      
The darkest evening of the year.      
      
He gives his harness bells a shake     
To ask if there is some mistake.      
The only other sound’s the sweep      
Of easy wind and downy flake.     
      
The woods are lovely, dark and deep.      
But I have promises to keep,      
And miles to go before I sleep,     
And miles to go before I sleep.      
  